//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.8009
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/", IsNullable=false)]
public partial class Merge {
    
    private MergeDocument[] itemsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Document")]
    public MergeDocument[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class MergeDocument {
    
    private string nameField;
    
    private MergeDocumentPart[] partField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Part")]
    public MergeDocumentPart[] Part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class MergeDocumentPart {
    
    private string nameField;
    
    private string idField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
