//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.8009
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/", IsNullable=false)]
public partial class Split {
    
    private SplitDocument[] itemsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Document")]
    public SplitDocument[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocument {
    
    private string nameField;
    
    private SplitDocumentPerson[] personField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public SplitDocumentPerson[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocumentPerson {
    
    private SplitDocumentPersonUniversalMarker[] universalMarkerField;
    
    private SplitDocumentPersonTextMarker[] textMarkerField;
    
    private SplitDocumentPersonTableMarker[] tableMarkerField;
    
    private SplitDocumentPersonPictureMarker[] pictureMarkerField;
    
    private string emailField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("UniversalMarker")]
    public SplitDocumentPersonUniversalMarker[] UniversalMarker {
        get {
            return this.universalMarkerField;
        }
        set {
            this.universalMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TextMarker")]
    public SplitDocumentPersonTextMarker[] TextMarker {
        get {
            return this.textMarkerField;
        }
        set {
            this.textMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TableMarker")]
    public SplitDocumentPersonTableMarker[] TableMarker {
        get {
            return this.tableMarkerField;
        }
        set {
            this.tableMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("PictureMarker")]
    public SplitDocumentPersonPictureMarker[] PictureMarker {
        get {
            return this.pictureMarkerField;
        }
        set {
            this.pictureMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocumentPersonUniversalMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocumentPersonTextMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocumentPersonTableMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocumentPersonPictureMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}
