//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/", IsNullable=false)]
public partial class Person {
    
    private PersonUniversalMarker[] universalMarkerField;
    
    private PersonListMarker[] listMarkerField;
    
    private PersonTableMarker[] tableMarkerField;
    
    private PersonPictureMarker[] pictureMarkerField;
    
    private PersonSheetMarker[] sheetMarkerField;
    
    private string emailField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("UniversalMarker")]
    public PersonUniversalMarker[] UniversalMarker {
        get {
            return this.universalMarkerField;
        }
        set {
            this.universalMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ListMarker")]
    public PersonListMarker[] ListMarker {
        get {
            return this.listMarkerField;
        }
        set {
            this.listMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TableMarker")]
    public PersonTableMarker[] TableMarker {
        get {
            return this.tableMarkerField;
        }
        set {
            this.tableMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("PictureMarker")]
    public PersonPictureMarker[] PictureMarker {
        get {
            return this.pictureMarkerField;
        }
        set {
            this.pictureMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("SheetMarker")]
    public PersonSheetMarker[] SheetMarker {
        get {
            return this.sheetMarkerField;
        }
        set {
            this.sheetMarkerField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class PersonUniversalMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class PersonListMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class PersonTableMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class PersonPictureMarker {
    
    private string elementIdField;
    
    private string selectionLastelementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
    
    /// <uwagi/>
    public string SelectionLastelementId {
        get {
            return this.selectionLastelementIdField;
        }
        set {
            this.selectionLastelementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class PersonSheetMarker {
    
    private string elementIdField;
    
    /// <uwagi/>
    public string ElementId {
        get {
            return this.elementIdField;
        }
        set {
            this.elementIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/", IsNullable=false)]
public partial class Split {
    
    private object[] itemsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Document", typeof(SplitDocument))]
    [System.Xml.Serialization.XmlElementAttribute("Excel", typeof(SplitExcel))]
    [System.Xml.Serialization.XmlElementAttribute("Person", typeof(Person))]
    [System.Xml.Serialization.XmlElementAttribute("Presentation", typeof(SplitPresentation))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitDocument {
    
    private string nameField;
    
    private Person[] personField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public Person[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitExcel {
    
    private string nameField;
    
    private Person[] personField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public Person[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://sourceforge.net/p/documenttransitionapp/svn/HEAD/tree/DocumentTransitionA" +
    "pp/")]
public partial class SplitPresentation {
    
    private string nameField;
    
    private Person[] personField;
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public Person[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}
