//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace DocumentTransitionUniversalApp.TransitionAppServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonFiles", Namespace="http://tempuri.org/")]
    public partial class PersonFiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PersonField;
        
        private string NameField;
        
        private byte[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartsSelectionTreeElement", Namespace="http://tempuri.org/")]
    public partial class PartsSelectionTreeElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IdField;
        
        private string ElementIdField;
        
        private System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> ChildsField;
        
        private string NameField;
        
        private int IndentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ElementId {
            get {
                return this.ElementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementIdField, value) != true)) {
                    this.ElementIdField = value;
                    this.RaisePropertyChanged("ElementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> Childs {
            get {
                return this.ChildsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildsField, value) != true)) {
                    this.ChildsField = value;
                    this.RaisePropertyChanged("Childs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Indent {
            get {
                return this.IndentField;
            }
            set {
                if ((this.IndentField.Equals(value) != true)) {
                    this.IndentField = value;
                    this.RaisePropertyChanged("Indent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransitionAppServices.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentResponse> SplitDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateSplitDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentResponse> GenerateSplitDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentResponse> MergeDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParts", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPartsResponse> GetPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitDocument", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequestBody Body;
        
        public SplitDocumentRequest() {
        }
        
        public SplitDocumentRequest(DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] docxFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] xmlFile;
        
        public SplitDocumentRequestBody() {
        }
        
        public SplitDocumentRequestBody(string docName, byte[] docxFile, byte[] xmlFile) {
            this.docName = docName;
            this.docxFile = docxFile;
            this.xmlFile = xmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentResponseBody Body;
        
        public SplitDocumentResponse() {
        }
        
        public SplitDocumentResponse(DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitDocumentResult;
        
        public SplitDocumentResponseBody() {
        }
        
        public SplitDocumentResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitDocumentResult) {
            this.SplitDocumentResult = SplitDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitDocument", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequestBody Body;
        
        public GenerateSplitDocumentRequest() {
        }
        
        public GenerateSplitDocumentRequest(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts;
        
        public GenerateSplitDocumentRequestBody() {
        }
        
        public GenerateSplitDocumentRequestBody(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            this.docName = docName;
            this.parts = parts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentResponseBody Body;
        
        public GenerateSplitDocumentResponse() {
        }
        
        public GenerateSplitDocumentResponse(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GenerateSplitDocumentResult;
        
        public GenerateSplitDocumentResponseBody() {
        }
        
        public GenerateSplitDocumentResponseBody(byte[] GenerateSplitDocumentResult) {
            this.GenerateSplitDocumentResult = GenerateSplitDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeDocument", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequestBody Body;
        
        public MergeDocumentRequest() {
        }
        
        public MergeDocumentRequest(DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files;
        
        public MergeDocumentRequestBody() {
        }
        
        public MergeDocumentRequestBody(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            this.docName = docName;
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentResponseBody Body;
        
        public MergeDocumentResponse() {
        }
        
        public MergeDocumentResponse(DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MergeDocumentResult;
        
        public MergeDocumentResponseBody() {
        }
        
        public MergeDocumentResponseBody(byte[] MergeDocumentResult) {
            this.MergeDocumentResult = MergeDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParts", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequestBody Body;
        
        public GetPartsRequest() {
        }
        
        public GetPartsRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] documentFile;
        
        public GetPartsRequestBody() {
        }
        
        public GetPartsRequestBody(string docName, byte[] documentFile) {
            this.docName = docName;
            this.documentFile = documentFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPartsResponseBody Body;
        
        public GetPartsResponse() {
        }
        
        public GetPartsResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetPartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetPartsResult;
        
        public GetPartsResponseBody() {
        }
        
        public GetPartsResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetPartsResult) {
            this.GetPartsResult = GetPartsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap>, DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient() : 
                base(Service1SoapClient.GetDefaultBinding(), Service1SoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.Service1Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.SplitDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequest request) {
            return base.Channel.SplitDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentResponse> SplitDocumentAsync(string docName, byte[] docxFile, byte[] xmlFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.SplitDocumentRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docxFile = docxFile;
            inValue.Body.xmlFile = xmlFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).SplitDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GenerateSplitDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequest request) {
            return base.Channel.GenerateSplitDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentResponse> GenerateSplitDocumentAsync(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitDocumentRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.parts = parts;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GenerateSplitDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.MergeDocumentAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequest request) {
            return base.Channel.MergeDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentResponse> MergeDocumentAsync(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.MergeDocumentRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.files = files;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).MergeDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPartsResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequest request) {
            return base.Channel.GetPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPartsResponse> GetPartsAsync(string docName, byte[] documentFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetPartsRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.documentFile = documentFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetPartsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:6943/TransitionAppServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1SoapClient.GetBindingForEndpoint(EndpointConfiguration.Service1Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1SoapClient.GetEndpointAddress(EndpointConfiguration.Service1Soap);
        }
        
        public enum EndpointConfiguration {
            
            Service1Soap,
        }
    }
}
