//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace DocumentTransitionUniversalApp.TransitionAppServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonFiles", Namespace="http://tempuri.org/")]
    public partial class PersonFiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PersonField;
        
        private string NameField;
        
        private byte[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartsSelectionTreeElement", Namespace="http://tempuri.org/")]
    public partial class PartsSelectionTreeElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IdField;
        
        private string ElementIdField;
        
        private DocumentTransitionUniversalApp.TransitionAppServices.ElementType TypeField;
        
        private System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> ChildsField;
        
        private string NameField;
        
        private int IndentField;
        
        private string OwnerNameField;
        
        private bool SelectedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ElementId {
            get {
                return this.ElementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementIdField, value) != true)) {
                    this.ElementIdField = value;
                    this.RaisePropertyChanged("ElementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public DocumentTransitionUniversalApp.TransitionAppServices.ElementType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> Childs {
            get {
                return this.ChildsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildsField, value) != true)) {
                    this.ChildsField = value;
                    this.RaisePropertyChanged("Childs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Indent {
            get {
                return this.IndentField;
            }
            set {
                if ((this.IndentField.Equals(value) != true)) {
                    this.IndentField = value;
                    this.RaisePropertyChanged("Indent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementType", Namespace="http://tempuri.org/")]
    public enum ElementType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paragraph = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulletList = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NumberedList = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hyperlink = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Picture = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sheet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Column = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Row = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cell = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Slide = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocumentTransitionUniversalApp.TransitionAppServices.ElementType))]
    public partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsErrorField;
        
        private string MessageField;
        
        private object DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransitionAppServices.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitWord", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitWordResponse> SplitWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitPresentation", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationResponse> SplitPresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateSplitWord", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordResponse> GenerateSplitWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateSplitPresentation", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationResponse> GenerateSplitPresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWordParts", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsResponse> GetWordPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPresentationParts", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsResponse> GetPresentationPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWordPartsFromXml", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlResponse> GetWordPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPresentationPartsFromXml", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlResponse> GetPresentationPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitExcel", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelResponse> SplitExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateSplitExcel", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelResponse> GenerateSplitExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExcelParts", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsResponse> GetExcelPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExcelPartsFromXml", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlResponse> GetExcelPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeWord", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeWordResponse> MergeWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergePresentation", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationResponse> MergePresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeExcel", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelResponse> MergeExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitWord", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequestBody Body;
        
        public SplitWordRequest() {
        }
        
        public SplitWordRequest(DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] docxFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] xmlFile;
        
        public SplitWordRequestBody() {
        }
        
        public SplitWordRequestBody(string docName, byte[] docxFile, byte[] xmlFile) {
            this.docName = docName;
            this.docxFile = docxFile;
            this.xmlFile = xmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitWordResponseBody Body;
        
        public SplitWordResponse() {
        }
        
        public SplitWordResponse(DocumentTransitionUniversalApp.TransitionAppServices.SplitWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitWordResult;
        
        public SplitWordResponseBody() {
        }
        
        public SplitWordResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitWordResult) {
            this.SplitWordResult = SplitWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitPresentationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitPresentation", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequestBody Body;
        
        public SplitPresentationRequest() {
        }
        
        public SplitPresentationRequest(DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitPresentationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] docFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] xmlFile;
        
        public SplitPresentationRequestBody() {
        }
        
        public SplitPresentationRequestBody(string docName, byte[] docFile, byte[] xmlFile) {
            this.docName = docName;
            this.docFile = docFile;
            this.xmlFile = xmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitPresentationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitPresentationResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationResponseBody Body;
        
        public SplitPresentationResponse() {
        }
        
        public SplitPresentationResponse(DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitPresentationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitPresentationResult;
        
        public SplitPresentationResponseBody() {
        }
        
        public SplitPresentationResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitPresentationResult) {
            this.SplitPresentationResult = SplitPresentationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitWord", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequestBody Body;
        
        public GenerateSplitWordRequest() {
        }
        
        public GenerateSplitWordRequest(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts;
        
        public GenerateSplitWordRequestBody() {
        }
        
        public GenerateSplitWordRequestBody(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            this.docName = docName;
            this.parts = parts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordResponseBody Body;
        
        public GenerateSplitWordResponse() {
        }
        
        public GenerateSplitWordResponse(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GenerateSplitWordResult;
        
        public GenerateSplitWordResponseBody() {
        }
        
        public GenerateSplitWordResponseBody(byte[] GenerateSplitWordResult) {
            this.GenerateSplitWordResult = GenerateSplitWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitPresentationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitPresentation", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequestBody Body;
        
        public GenerateSplitPresentationRequest() {
        }
        
        public GenerateSplitPresentationRequest(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitPresentationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts;
        
        public GenerateSplitPresentationRequestBody() {
        }
        
        public GenerateSplitPresentationRequestBody(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            this.docName = docName;
            this.parts = parts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitPresentationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitPresentationResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationResponseBody Body;
        
        public GenerateSplitPresentationResponse() {
        }
        
        public GenerateSplitPresentationResponse(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitPresentationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GenerateSplitPresentationResult;
        
        public GenerateSplitPresentationResponseBody() {
        }
        
        public GenerateSplitPresentationResponseBody(byte[] GenerateSplitPresentationResult) {
            this.GenerateSplitPresentationResult = GenerateSplitPresentationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordParts", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequestBody Body;
        
        public GetWordPartsRequest() {
        }
        
        public GetWordPartsRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordPartsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] documentFile;
        
        public GetWordPartsRequestBody() {
        }
        
        public GetWordPartsRequestBody(string docName, byte[] documentFile) {
            this.docName = docName;
            this.documentFile = documentFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordPartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsResponseBody Body;
        
        public GetWordPartsResponse() {
        }
        
        public GetWordPartsResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordPartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetWordPartsResult;
        
        public GetWordPartsResponseBody() {
        }
        
        public GetWordPartsResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetWordPartsResult) {
            this.GetWordPartsResult = GetWordPartsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPresentationPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPresentationParts", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequestBody Body;
        
        public GetPresentationPartsRequest() {
        }
        
        public GetPresentationPartsRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPresentationPartsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string preName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] presentationFile;
        
        public GetPresentationPartsRequestBody() {
        }
        
        public GetPresentationPartsRequestBody(string preName, byte[] presentationFile) {
            this.preName = preName;
            this.presentationFile = presentationFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPresentationPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPresentationPartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsResponseBody Body;
        
        public GetPresentationPartsResponse() {
        }
        
        public GetPresentationPartsResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPresentationPartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetPresentationPartsResult;
        
        public GetPresentationPartsResponseBody() {
        }
        
        public GetPresentationPartsResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetPresentationPartsResult) {
            this.GetPresentationPartsResult = GetPresentationPartsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordPartsFromXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordPartsFromXml", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequestBody Body;
        
        public GetWordPartsFromXmlRequest() {
        }
        
        public GetWordPartsFromXmlRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordPartsFromXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] documentFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] splitFile;
        
        public GetWordPartsFromXmlRequestBody() {
        }
        
        public GetWordPartsFromXmlRequestBody(string docName, byte[] documentFile, byte[] splitFile) {
            this.docName = docName;
            this.documentFile = documentFile;
            this.splitFile = splitFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordPartsFromXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordPartsFromXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlResponseBody Body;
        
        public GetWordPartsFromXmlResponse() {
        }
        
        public GetWordPartsFromXmlResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordPartsFromXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetWordPartsFromXmlResult;
        
        public GetWordPartsFromXmlResponseBody() {
        }
        
        public GetWordPartsFromXmlResponseBody(DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetWordPartsFromXmlResult) {
            this.GetWordPartsFromXmlResult = GetWordPartsFromXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPresentationPartsFromXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPresentationPartsFromXml", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequestBody Body;
        
        public GetPresentationPartsFromXmlRequest() {
        }
        
        public GetPresentationPartsFromXmlRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPresentationPartsFromXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] documentFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] splitFile;
        
        public GetPresentationPartsFromXmlRequestBody() {
        }
        
        public GetPresentationPartsFromXmlRequestBody(string docName, byte[] documentFile, byte[] splitFile) {
            this.docName = docName;
            this.documentFile = documentFile;
            this.splitFile = splitFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPresentationPartsFromXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPresentationPartsFromXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlResponseBody Body;
        
        public GetPresentationPartsFromXmlResponse() {
        }
        
        public GetPresentationPartsFromXmlResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPresentationPartsFromXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetPresentationPartsFromXmlResult;
        
        public GetPresentationPartsFromXmlResponseBody() {
        }
        
        public GetPresentationPartsFromXmlResponseBody(DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetPresentationPartsFromXmlResult) {
            this.GetPresentationPartsFromXmlResult = GetPresentationPartsFromXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitExcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitExcel", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequestBody Body;
        
        public SplitExcelRequest() {
        }
        
        public SplitExcelRequest(DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitExcelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] docFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] xmlFile;
        
        public SplitExcelRequestBody() {
        }
        
        public SplitExcelRequestBody(string docName, byte[] docFile, byte[] xmlFile) {
            this.docName = docName;
            this.docFile = docFile;
            this.xmlFile = xmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitExcelResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelResponseBody Body;
        
        public SplitExcelResponse() {
        }
        
        public SplitExcelResponse(DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitExcelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitExcelResult;
        
        public SplitExcelResponseBody() {
        }
        
        public SplitExcelResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> SplitExcelResult) {
            this.SplitExcelResult = SplitExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitExcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitExcel", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequestBody Body;
        
        public GenerateSplitExcelRequest() {
        }
        
        public GenerateSplitExcelRequest(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitExcelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts;
        
        public GenerateSplitExcelRequestBody() {
        }
        
        public GenerateSplitExcelRequestBody(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            this.docName = docName;
            this.parts = parts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateSplitExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateSplitExcelResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelResponseBody Body;
        
        public GenerateSplitExcelResponse() {
        }
        
        public GenerateSplitExcelResponse(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateSplitExcelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GenerateSplitExcelResult;
        
        public GenerateSplitExcelResponseBody() {
        }
        
        public GenerateSplitExcelResponseBody(byte[] GenerateSplitExcelResult) {
            this.GenerateSplitExcelResult = GenerateSplitExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExcelPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExcelParts", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequestBody Body;
        
        public GetExcelPartsRequest() {
        }
        
        public GetExcelPartsRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExcelPartsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string excName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] excelFile;
        
        public GetExcelPartsRequestBody() {
        }
        
        public GetExcelPartsRequestBody(string excName, byte[] excelFile) {
            this.excName = excName;
            this.excelFile = excelFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExcelPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExcelPartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsResponseBody Body;
        
        public GetExcelPartsResponse() {
        }
        
        public GetExcelPartsResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExcelPartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetExcelPartsResult;
        
        public GetExcelPartsResponseBody() {
        }
        
        public GetExcelPartsResponseBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> GetExcelPartsResult) {
            this.GetExcelPartsResult = GetExcelPartsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExcelPartsFromXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExcelPartsFromXml", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequestBody Body;
        
        public GetExcelPartsFromXmlRequest() {
        }
        
        public GetExcelPartsFromXmlRequest(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExcelPartsFromXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] documentFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] splitFile;
        
        public GetExcelPartsFromXmlRequestBody() {
        }
        
        public GetExcelPartsFromXmlRequestBody(string docName, byte[] documentFile, byte[] splitFile) {
            this.docName = docName;
            this.documentFile = documentFile;
            this.splitFile = splitFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExcelPartsFromXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExcelPartsFromXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlResponseBody Body;
        
        public GetExcelPartsFromXmlResponse() {
        }
        
        public GetExcelPartsFromXmlResponse(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExcelPartsFromXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetExcelPartsFromXmlResult;
        
        public GetExcelPartsFromXmlResponseBody() {
        }
        
        public GetExcelPartsFromXmlResponseBody(DocumentTransitionUniversalApp.TransitionAppServices.ServiceResponse GetExcelPartsFromXmlResult) {
            this.GetExcelPartsFromXmlResult = GetExcelPartsFromXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeWord", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequestBody Body;
        
        public MergeWordRequest() {
        }
        
        public MergeWordRequest(DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files;
        
        public MergeWordRequestBody() {
        }
        
        public MergeWordRequestBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeWordResponseBody Body;
        
        public MergeWordResponse() {
        }
        
        public MergeWordResponse(DocumentTransitionUniversalApp.TransitionAppServices.MergeWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MergeWordResult;
        
        public MergeWordResponseBody() {
        }
        
        public MergeWordResponseBody(byte[] MergeWordResult) {
            this.MergeWordResult = MergeWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergePresentationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergePresentation", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequestBody Body;
        
        public MergePresentationRequest() {
        }
        
        public MergePresentationRequest(DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergePresentationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files;
        
        public MergePresentationRequestBody() {
        }
        
        public MergePresentationRequestBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergePresentationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergePresentationResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationResponseBody Body;
        
        public MergePresentationResponse() {
        }
        
        public MergePresentationResponse(DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergePresentationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MergePresentationResult;
        
        public MergePresentationResponseBody() {
        }
        
        public MergePresentationResponseBody(byte[] MergePresentationResult) {
            this.MergePresentationResult = MergePresentationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeExcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeExcel", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequestBody Body;
        
        public MergeExcelRequest() {
        }
        
        public MergeExcelRequest(DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeExcelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files;
        
        public MergeExcelRequestBody() {
        }
        
        public MergeExcelRequestBody(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeExcelResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelResponseBody Body;
        
        public MergeExcelResponse() {
        }
        
        public MergeExcelResponse(DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeExcelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MergeExcelResult;
        
        public MergeExcelResponseBody() {
        }
        
        public MergeExcelResponseBody(byte[] MergeExcelResult) {
            this.MergeExcelResult = MergeExcelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap>, DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient() : 
                base(Service1SoapClient.GetDefaultBinding(), Service1SoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.Service1Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitWordResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.SplitWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequest request) {
            return base.Channel.SplitWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitWordResponse> SplitWordAsync(string docName, byte[] docxFile, byte[] xmlFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.SplitWordRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docxFile = docxFile;
            inValue.Body.xmlFile = xmlFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).SplitWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.SplitPresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequest request) {
            return base.Channel.SplitPresentationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationResponse> SplitPresentationAsync(string docName, byte[] docFile, byte[] xmlFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.SplitPresentationRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docFile = docFile;
            inValue.Body.xmlFile = xmlFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).SplitPresentationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GenerateSplitWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequest request) {
            return base.Channel.GenerateSplitWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordResponse> GenerateSplitWordAsync(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitWordRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.parts = parts;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GenerateSplitWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GenerateSplitPresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequest request) {
            return base.Channel.GenerateSplitPresentationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationResponse> GenerateSplitPresentationAsync(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitPresentationRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.parts = parts;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GenerateSplitPresentationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetWordPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequest request) {
            return base.Channel.GetWordPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsResponse> GetWordPartsAsync(string docName, byte[] documentFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.documentFile = documentFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetWordPartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetPresentationPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequest request) {
            return base.Channel.GetPresentationPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsResponse> GetPresentationPartsAsync(string preName, byte[] presentationFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsRequestBody();
            inValue.Body.preName = preName;
            inValue.Body.presentationFile = presentationFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetPresentationPartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetWordPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequest request) {
            return base.Channel.GetWordPartsFromXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlResponse> GetWordPartsFromXmlAsync(string docName, byte[] documentFile, byte[] splitFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetWordPartsFromXmlRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.documentFile = documentFile;
            inValue.Body.splitFile = splitFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetWordPartsFromXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetPresentationPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequest request) {
            return base.Channel.GetPresentationPartsFromXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlResponse> GetPresentationPartsFromXmlAsync(string docName, byte[] documentFile, byte[] splitFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetPresentationPartsFromXmlRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.documentFile = documentFile;
            inValue.Body.splitFile = splitFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetPresentationPartsFromXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.SplitExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequest request) {
            return base.Channel.SplitExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelResponse> SplitExcelAsync(string docName, byte[] docFile, byte[] xmlFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.SplitExcelRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docFile = docFile;
            inValue.Body.xmlFile = xmlFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).SplitExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GenerateSplitExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequest request) {
            return base.Channel.GenerateSplitExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelResponse> GenerateSplitExcelAsync(string docName, System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PartsSelectionTreeElement> parts) {
            DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GenerateSplitExcelRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.parts = parts;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GenerateSplitExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetExcelPartsAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequest request) {
            return base.Channel.GetExcelPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsResponse> GetExcelPartsAsync(string excName, byte[] excelFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsRequestBody();
            inValue.Body.excName = excName;
            inValue.Body.excelFile = excelFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetExcelPartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.GetExcelPartsFromXmlAsync(DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequest request) {
            return base.Channel.GetExcelPartsFromXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlResponse> GetExcelPartsFromXmlAsync(string docName, byte[] documentFile, byte[] splitFile) {
            DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.GetExcelPartsFromXmlRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.documentFile = documentFile;
            inValue.Body.splitFile = splitFile;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).GetExcelPartsFromXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeWordResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.MergeWordAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequest request) {
            return base.Channel.MergeWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeWordResponse> MergeWordAsync(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.MergeWordRequestBody();
            inValue.Body.files = files;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).MergeWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.MergePresentationAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequest request) {
            return base.Channel.MergePresentationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationResponse> MergePresentationAsync(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.MergePresentationRequestBody();
            inValue.Body.files = files;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).MergePresentationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelResponse> DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap.MergeExcelAsync(DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequest request) {
            return base.Channel.MergeExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelResponse> MergeExcelAsync(System.Collections.ObjectModel.ObservableCollection<DocumentTransitionUniversalApp.TransitionAppServices.PersonFiles> files) {
            DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequest inValue = new DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequest();
            inValue.Body = new DocumentTransitionUniversalApp.TransitionAppServices.MergeExcelRequestBody();
            inValue.Body.files = files;
            return ((DocumentTransitionUniversalApp.TransitionAppServices.Service1Soap)(this)).MergeExcelAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:6943/TransitionAppServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1SoapClient.GetBindingForEndpoint(EndpointConfiguration.Service1Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1SoapClient.GetEndpointAddress(EndpointConfiguration.Service1Soap);
        }
        
        public enum EndpointConfiguration {
            
            Service1Soap,
        }
    }
}
