//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentTransitionApp.TransitionAppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonFiles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonFiles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DocumentTransitionApp.TransitionAppService.FileData[] FilesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DocumentTransitionApp.TransitionAppService.FileData[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransitionAppService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name docName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitDocument", ReplyAction="*")]
        DocumentTransitionApp.TransitionAppService.SplitDocumentResponse SplitDocument(DocumentTransitionApp.TransitionAppService.SplitDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SplitDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.SplitDocumentResponse> SplitDocumentAsync(DocumentTransitionApp.TransitionAppService.SplitDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name files from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeDocument", ReplyAction="*")]
        DocumentTransitionApp.TransitionAppService.MergeDocumentResponse MergeDocument(DocumentTransitionApp.TransitionAppService.MergeDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.MergeDocumentResponse> MergeDocumentAsync(DocumentTransitionApp.TransitionAppService.MergeDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitDocument", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionApp.TransitionAppService.SplitDocumentRequestBody Body;
        
        public SplitDocumentRequest() {
        }
        
        public SplitDocumentRequest(DocumentTransitionApp.TransitionAppService.SplitDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] docxFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] xmlFile;
        
        public SplitDocumentRequestBody() {
        }
        
        public SplitDocumentRequestBody(string docName, byte[] docxFile, byte[] xmlFile) {
            this.docName = docName;
            this.docxFile = docxFile;
            this.xmlFile = xmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SplitDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SplitDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionApp.TransitionAppService.SplitDocumentResponseBody Body;
        
        public SplitDocumentResponse() {
        }
        
        public SplitDocumentResponse(DocumentTransitionApp.TransitionAppService.SplitDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SplitDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentTransitionApp.TransitionAppService.PersonFiles[] SplitDocumentResult;
        
        public SplitDocumentResponseBody() {
        }
        
        public SplitDocumentResponseBody(DocumentTransitionApp.TransitionAppService.PersonFiles[] SplitDocumentResult) {
            this.SplitDocumentResult = SplitDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeDocument", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionApp.TransitionAppService.MergeDocumentRequestBody Body;
        
        public MergeDocumentRequest() {
        }
        
        public MergeDocumentRequest(DocumentTransitionApp.TransitionAppService.MergeDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DocumentTransitionApp.TransitionAppService.PersonFiles[] files;
        
        public MergeDocumentRequestBody() {
        }
        
        public MergeDocumentRequestBody(DocumentTransitionApp.TransitionAppService.PersonFiles[] files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DocumentTransitionApp.TransitionAppService.MergeDocumentResponseBody Body;
        
        public MergeDocumentResponse() {
        }
        
        public MergeDocumentResponse(DocumentTransitionApp.TransitionAppService.MergeDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MergeDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MergeDocumentResult;
        
        public MergeDocumentResponseBody() {
        }
        
        public MergeDocumentResponseBody(byte[] MergeDocumentResult) {
            this.MergeDocumentResult = MergeDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : DocumentTransitionApp.TransitionAppService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<DocumentTransitionApp.TransitionAppService.Service1Soap>, DocumentTransitionApp.TransitionAppService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentTransitionApp.TransitionAppService.SplitDocumentResponse DocumentTransitionApp.TransitionAppService.Service1Soap.SplitDocument(DocumentTransitionApp.TransitionAppService.SplitDocumentRequest request) {
            return base.Channel.SplitDocument(request);
        }
        
        public DocumentTransitionApp.TransitionAppService.PersonFiles[] SplitDocument(string docName, byte[] docxFile, byte[] xmlFile) {
            DocumentTransitionApp.TransitionAppService.SplitDocumentRequest inValue = new DocumentTransitionApp.TransitionAppService.SplitDocumentRequest();
            inValue.Body = new DocumentTransitionApp.TransitionAppService.SplitDocumentRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docxFile = docxFile;
            inValue.Body.xmlFile = xmlFile;
            DocumentTransitionApp.TransitionAppService.SplitDocumentResponse retVal = ((DocumentTransitionApp.TransitionAppService.Service1Soap)(this)).SplitDocument(inValue);
            return retVal.Body.SplitDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.SplitDocumentResponse> DocumentTransitionApp.TransitionAppService.Service1Soap.SplitDocumentAsync(DocumentTransitionApp.TransitionAppService.SplitDocumentRequest request) {
            return base.Channel.SplitDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.SplitDocumentResponse> SplitDocumentAsync(string docName, byte[] docxFile, byte[] xmlFile) {
            DocumentTransitionApp.TransitionAppService.SplitDocumentRequest inValue = new DocumentTransitionApp.TransitionAppService.SplitDocumentRequest();
            inValue.Body = new DocumentTransitionApp.TransitionAppService.SplitDocumentRequestBody();
            inValue.Body.docName = docName;
            inValue.Body.docxFile = docxFile;
            inValue.Body.xmlFile = xmlFile;
            return ((DocumentTransitionApp.TransitionAppService.Service1Soap)(this)).SplitDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocumentTransitionApp.TransitionAppService.MergeDocumentResponse DocumentTransitionApp.TransitionAppService.Service1Soap.MergeDocument(DocumentTransitionApp.TransitionAppService.MergeDocumentRequest request) {
            return base.Channel.MergeDocument(request);
        }
        
        public byte[] MergeDocument(DocumentTransitionApp.TransitionAppService.PersonFiles[] files) {
            DocumentTransitionApp.TransitionAppService.MergeDocumentRequest inValue = new DocumentTransitionApp.TransitionAppService.MergeDocumentRequest();
            inValue.Body = new DocumentTransitionApp.TransitionAppService.MergeDocumentRequestBody();
            inValue.Body.files = files;
            DocumentTransitionApp.TransitionAppService.MergeDocumentResponse retVal = ((DocumentTransitionApp.TransitionAppService.Service1Soap)(this)).MergeDocument(inValue);
            return retVal.Body.MergeDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.MergeDocumentResponse> DocumentTransitionApp.TransitionAppService.Service1Soap.MergeDocumentAsync(DocumentTransitionApp.TransitionAppService.MergeDocumentRequest request) {
            return base.Channel.MergeDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentTransitionApp.TransitionAppService.MergeDocumentResponse> MergeDocumentAsync(DocumentTransitionApp.TransitionAppService.PersonFiles[] files) {
            DocumentTransitionApp.TransitionAppService.MergeDocumentRequest inValue = new DocumentTransitionApp.TransitionAppService.MergeDocumentRequest();
            inValue.Body = new DocumentTransitionApp.TransitionAppService.MergeDocumentRequestBody();
            inValue.Body.files = files;
            return ((DocumentTransitionApp.TransitionAppService.Service1Soap)(this)).MergeDocumentAsync(inValue);
        }
    }
}
